version: '3.7'

services:
  mongo:
    container_name: mongo_user_request_counter
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: urc-password
      MONGO_INITDB_DATABASE: urcdb
    volumes:
      - urc_mongo_volume:/data/db

volumes:
  urc_mongo_volume: